config/routes.rb
Rails.application.routes.draw do
  resources :memos

  get 'map/index'

  get 'pages/index'

   devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  get 'pages/show'

  get 'map/index'
  root 'map#index'
  get "map/index"
  post "map/index" => "map#post_memo"
  

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]

    def self.from_omniauth(auth)
        where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.username = auth["info"]["nickname"]
        end
    end

    def self.new_with_session(params, session)
        if session["devise.user_attributes"]
            new(session["devise.user_attributes"], without_protection: true) do |user|
                user.attributes = params
                user.valid?
            end
        else
            super
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    map_index_path
  end

  private
  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
    def index
    # @memos = User.all
    # @memos =Memo.all
    # session["init"] = true ;
  
    p session[:id] ;
    p cookies[:user_name] ;
    # binding.pry ;
    # @user = User.find(session[:id])
    # @user=Player.find(8)
    # @memos =Memo.where(user_id:session[:user_id])
    @memos =Memo.where(user_id:session[:id])
    begin
    @hash = Gmaps4rails.build_markers(@memos) do |user, marker|
      # 以下　marker [key] [value]のように指定可能
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow user.description
     # marker.infowindow "<b>" + "test" + "</b> <button type='button' name='eee' value = 'eee'></button> "

      # marker.infowindow '<form action="/posts/1" class="button_to" data-remote="true" method="post">
      # <div><input type="submit" value="A post"></div>
      # </form>'
      if user.description == nil
        user.description = ""
      end 
      marker.title user.description
      marker.infowindow '<form action="/map/index" data-remote="true" method="post"><div><textarea name="memo" style="height:5em">'+user.description+'</textarea></div><div><input type="hidden" name="id" value= '+user.id.to_s+' ></div><div><input type="submit" name="add" value="save" onClick="location.reload();"><input type="submit" name="delete" value="delete" onClick="location.reload();"></div></form>'

      # pic_info ={
      #             "url" => 'http://www.planet-action.org/img/2009/interieur/bg_titre_open.png', 
      #             "width" =>  32, 
      #             "height" => 32
      #           }
      # marker.picture pic_info 
      marker.json({title: user.title})
      # marker.json({title: "test"})
      puts "###########################"
      # marker.id id.to_s
    end


  rescue
    binding.pry ;
  end
  end


  #
  # === 地点データ保存用
  #
  def post_memo
    is_double_add = false 
    all_memo = Memo.all ;
    all_memo.each do |m|
    if ( params["lng"].to_f == m.longitude && params["lat"].to_f == m.latitude )
       is_double_add = true 
     end

    end

    if !is_double_add
      if params["add"] != nil #メモの追加
        add_memo(params, session[:user_id]) ;
      elsif params["delete"] != nil
        delete_memo(params)  ;
      end
    end

    # render("/map/index")
    # redirect_to('/')
    # redirect_to(:back)
  end


  #
  # === メモの追加
  #
  def add_memo(params, user_id)
    if params["id"] != "new"  #すでにメモが登録してある場合
      @memo = Memo.find(params["id"])
      @memo.description = params["memo"]
      @memo.save
    else        #新規に登録の場合
      @memo= Memo.new(latitude:params["lat"], longitude:params["lng"], description:params[:memo], user_id:user_id ) ;
      @memo.save
    end
  end

  #
  # === メモの削除
  #
  def delete_memo(params)
      @memo = Memo.find(params["id"])
      @memo.delete
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @memos = Memo.all
    respond_with(@memos)
  end

  def show
    respond_with(@memo)
  end

  def new
    @memo = Memo.new
    respond_with(@memo)
  end

  def edit
  end

  def create
    @memo = Memo.new(memo_params)
    @memo.save
    respond_with(@memo)
  end

  def update
    @memo.update(memo_params)
    respond_with(@memo)
  end

  def destroy
    @memo.destroy
    respond_with(@memo)
  end

  private
    def set_memo
      @memo = Memo.find(params[:id])
    end

    def memo_params
      params.require(:memo).permit(:title, :description, :address, :latitude, :longitude, :user_id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

        if @user.persisted?
            flash.notice = "ログインしました！"
            sign_in_and_redirect @user
        else
            session["devise.user_attributes"] = @user.attributes
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src="https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js"></script>

    <head>

        <%= stylesheet_link_tag 'application', media: 'all',
            'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <title>DeviseQiita</title>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">カフェログ</a>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">Info</a></li>
                        <% if user_signed_in? %>
                            <!-- <strong<%= link_to current_user.username, pages_show_path %></strong> -->
                            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                            <li> <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                        <% else %>
                            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
                            <li><%= link_to 'ログイン', new_user_session_path %></li>

                        <% end %>
                    </ul>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul id="navbar-list-menu" class="nav navbar-nav navbar-right">
                        <!-- スマホ用のメニュー部分 -->
                        <%# <%= sidebar_list_items() %>
                    </ul>
                </div>
            </div>
        </div>


        <div id="main" class="container-fluid">
            <div class="row">
                <div class="col-xs-2 col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <!-- PC用のメニュー部分 -->
                        Test
                        <%= yield(:sidebar) %>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-3 col-md-2" style='width: 700px; height: 400px;'>

                    <!-- <div class="col&#45;sm&#45;9 col&#45;sm&#45;offset&#45;3 col&#45;md&#45;10 col&#45;md&#45;offset&#45;2 main"> -->
                    <%= yield %>
                    <div id="info">
                        <h1>test</h1>
                    </div>

                    </div>
                    <div class="col-xs-2 col-sm-3 col-md-2 sidebar">
                        <ul class="nav nav-sidebar">
                            Test
                            <!-- PC用のメニュー部分 -->
                            <%= yield(:right_side) %>
                        </ul>
                    </div>
                    <!-- </div> -->
            </div>
        </div>

    </body>


</html>

app/views/map/index.html.erb
<!-- <div style='width: 800px;'> -->
<h2>map</h2>
<div id="map" style='width: 600px; height: 400px;'></div>
  <!-- <div id="map" style='width: 600px; height: 400px;'></div> -->
  <!-- <div id="map" style='width: 300px; height: 200px;'></div> -->
<!-- </div> -->
<%# <%= puts params %> 
<%# <%= "srere#{Time.now}" %> 

<!-- データの表示部 -->
<!-- <div class="form&#45;actions"> -->
<!--     <!&#45;&#45; PC用のメニュー部分 &#45;&#45;> -->
<!--     <!&#45;&#45; <input type= "tel" name="title"><br> &#45;&#45;> -->
<!--     <input id="content" type= "tel" name="context", value="ddd"> -->
<!-- </div> -->


<script type="text/javascript">
var title_hash = {} ;
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = null ;
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    //マップのタッチ判定 以下はタッチしたら入る
    google.maps.event.addListener(handler.getMap(),  'click', function(e){
        markers = handler.addMarkers([    // put marker method
                {
                    "lat": e.latLng.lat() ,     // coordinates from parameter company
                    "lng":e.latLng.lng(), 
                    "infowindow": '<form id="demo-sec" action="/map/index" data-remote="true" method="post"><div><textarea name="memo" style="height:5em" wrap="hard" ></textarea></div><div><input type="hidden" name="id" value= "new" ><div><input type="hidden" name="lat" value= '+e.latLng.lat()+' ></div><div><input type="hidden" name="lng" value= '+e.latLng.lng()+' ></div> <input type="submit" name="add" value="save" onClick="location.reload(false);" > </form>'

                }
        ]) ;

        handler.bounds.extendWith(markers);
        }) ;

        // 以下で各markerにイベントリスナーをつける
        for (var i=0 ;i < markers.length ; i++) {
            var marker = markers[i]  ;
            console.log(marker) ;
        }

});

function CenterControl(controlDiv, map){

var now_pos ;
navigator.geolocation.getCurrentPosition(function(position){
        now_pos = new google.maps.LatLng(position.coords.latitude,  position.coords.longitude) ;
}) ;

// Set CSS for the control border.
var controlUI = document.createElement('div') ;
// controlUI.style.backgroundColor = '#fff' ;
controlUI.style.backgroundColor = '#000' ;
controlUI.style.border = '2px solid #000' ;
controlUI.style.borderRadius = '3px' ;
controlUI.style.boxShadow = '0 2px 6px rgba(0, 0, 0, .3)' ;
controlUI.style.cursor = 'pointer' ;
controlUI.style.marginBottom = '22px' ;
controlUI.style.textAlign = 'center' ;
controlUI.title = 'Click to recenter the map' ;
controlDiv.appendChild(controlUI) ;

// Set CSS for the control interior.
var controlText = document.createElement('div') ;
// controlText.style.color = 'rgb(25, 25, 25)' ;
controlText.style.color = 'rgb(256, 256, 256)' ;
controlText.style.fontFamily = 'Roboto, Arial, sans-serif' ;
controlText.style.fontSize = '16px' ;
controlText.style.lineHeight = '38px' ;
controlText.style.paddingLeft = '5px' ;
controlText.style.paddingRight = '5px' ;
controlText.innerHTML = '現在地' ;
controlUI.appendChild(controlText) ;
// Setup the click event listeners: simply set the map to Chicago.



controlUI.addEventListener('click',  function() {
        map.setCenter(now_pos) ;
        map.setZoom(14)  //ズームレベル
        }) ;
}

var map = handler.getMap() ;
var centerControlDiv = document.createElement('div') ;
var centerControl = new CenterControl(centerControlDiv,  map) ;
map.controls[google.maps.ControlPosition.TOP_CENTER].push(centerControlDiv) ;



function onClick_delete_memo(){

}

</script>

                            <% content_for :sidebar do %>
                            <h2>Profile</h2>
                                <%= @user%>
                            <% end %>


<% content_for :right_side do %>
                            <h4>周辺のカフェ</h4>
                                <% @hash.each do |h| %>
                                    <%= h[:marker_title] %>
                                    <br>
                                <% end %>
                            <% end %>

app/views/memos/_form.html.erb
<%= form_for(@memo) do |f| %>
  <% if @memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing memo</h1>

<%= render 'form' %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<h1>Listing memos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.title %></td>
        <td><%= memo.description %></td>
        <td><%= memo.address %></td>
        <td><%= memo.latitude %></td>
        <td><%= memo.longitude %></td>
        <td><%= memo.user_id %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New memo</h1>

<%= render 'form' %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @memo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @memo.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @memo.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @memo.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @memo.longitude %>
</p>

<p>
  <strong>User:</strong>
  <%= @memo.user_id %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>